version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_KEY=${JWT_KEY}
      - CAPTCHA_SECRET_KEY=${CAPTCHA_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_CAPTCHA_SITE_KEY: ${VITE_APP_CAPTCHA_SITE_KEY}
    ports:
      - "5173:80"
    depends_on:
      - backend
    
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: nutukoira
      POSTGRES_PASSWORD: SecureDatabasePassword!1
      POSTGRES_DB: secure_directory
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
